### ISSUE TITLE
About data format

### ISSUE THREAD

**Issue by wntg** [wonjune-kang/llm-speech-summarization#1]
Thanks for your great work！
Can you give us a sample about dataset format ?

**Comment by jeeyung** [comment]
I also wonder how you run inference code. Which type of audio input you used?

**Comment by wonjune-kang** [comment]
> Thanks for your great work！ Can you give us a sample about dataset format ?

Thanks for your interest in the work! I've cleaned up and added the code for the Librispeech dataset preprocessing pipeline and updated the README with instructions.

> I also wonder how you run inference code. Which type of audio input you used?

You can run inference by loading in any audio signal (wav, mp3, etc.) using, for example, ```librosa.load```. I've added an example of how to run this in ```inference.py``` and also added this to the README.

**Comment by wntg** [comment]
Perfect！

**Comment by wntg** [comment]
In order to learn large speech models, we established a WeChat communication group. Most are beginners. I started learning from this project, and it felt like a good start. If you are interested, we welcome you to join the group and give us guidance.

**Comment by wonjune-kang** [comment]
I don't use WeChat unfortunately, so I'm afraid I'll have to pass on your offer. Thank you for the invitation though, and I hope that this repo and the paper are helpful for your group!
