### ISSUE TITLE
Inference using a wav file fails

### ISSUE THREAD

**Issue by uni-manjunath-ke** [wonjune-kang/llm-speech-summarization#6]
cmd: python inference.py -c config/config_full.yaml -g 0   -p ../speech_llm_audio_encoder.pt   -a  /repos/ds-e2e-asr-testing/sample_audios/57.wav

I get below error:
  File "/repos/prompt/speechllm/sp_llm_summary/llm-speech-summarization/inference.py", line 211, in <module>
    llm_inferencer = LLMSpeechTextInference(
  File "/repos/prompt/speechllm/sp_llm_summary/llm-speech-summarization/inference.py", line 21, in __init__
    self.audio_encoder.load_state_dict(checkpoint["audio_encoder"])
KeyError: 'audio_encoder'

 There is no key called : 'audio_encoder' in  ../speech_llm_audio_encoder.pt  that was loaded. Pls suggest ASAP. Thanks 
 @wonjune-kang

**Comment by wonjune-kang** [comment]
Hi, thanks for raising this issue. This was resolved in the most recent commit a few weeks ago; could you pull the latest version of the repo and try again?

**Comment by uni-manjunath-ke** [comment]
Thanks. Pulling latest repo works.
